#ifndef  SETPOINT_H
#define  SETPOINT_H


typedef enum {
    SM_NO_EVENT = 0,
    SM_NORMAL_STATE = 1,
    SM_HIGH_SWITCHING_STATE = 2,
    SM_LOW_SWITCHING_STATE = 3,
    SM_HIGH_ALARM_STATE = 4, 
    SM_LOW_ALARM_STATE =5
}MeasurementStates_t;

typedef enum {
    NO_EVENT = 0,
    NORMAL_TO_HIGH_SWITCH_EVENT,
    NORMAL_TO_LOW_SWITCH_EVENT,
    HIGH_SWITCH_TO_HIGH_ALARM_EVENT,
    HIGH_SWITCH_TO_NORMAL_EVENT,
    HIGH_ALARM_TO_NORMAL_EVENT,
    LOW_SWITCH_TO_LOW_ALARM_EVENT,
    LOW_SWITCH_TO_NORMAL_EVENT,
    LOW_ALARM_TO_NORMAL_EVENT,
}MeasurementEvent_t;


#endif // ! SETPOINT_H
